name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          node-version-file: 'package.json'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - run: npm ci --legacy-peer-deps
      - run: npm run build
      - run: npm run build:prod
      - run: npm test
      - name: E2E_FireFox
        uses: cypress-io/github-action@v6.7.0
        with:
          browser: firefox
          start: npm start
      - name: E2E_Chrome
        uses: cypress-io/github-action@v6.7.0
        with:
          browser: chrome
          start: npm start
